#ifndef PLANTLOGGERDLL_GLOBAL_H
#define PLANTLOGGERDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLANTLOGGERDLL_LIBRARY)
#  define PLANTLOGGERDLL_EXPORT Q_DECL_EXPORT
#else
#  define PLANTLOGGERDLL_EXPORT Q_DECL_IMPORT
#endif

#endif // PLANTLOGGERDLL_GLOBAL_H
